"""initial schema

Revision ID: 9e504c864be4
Revises: 
Create Date: 2026-05-28 23:06:19.939228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e504c864be4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('spoolman_id', sa.Integer(), nullable=True),
    sa.Column('filamentdb_filament_id', sa.String(length=24), nullable=True),
    sa.Column('filamentdb_spool_id', sa.String(length=24), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('spoolman_value', sa.Text(), nullable=True),
    sa.Column('filamentdb_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filament_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoolman_filament_id', sa.Integer(), nullable=False),
    sa.Column('filamentdb_id', sa.String(length=24), nullable=False),
    sa.Column('filamentdb_parent_id', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolman_filament_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'entity_type', 'entity_id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('spoolman_id', sa.Integer(), nullable=True),
    sa.Column('filamentdb_filament_id', sa.String(length=24), nullable=True),
    sa.Column('filamentdb_spool_id', sa.String(length=24), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spool_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoolman_spool_id', sa.Integer(), nullable=False),
    sa.Column('filamentdb_filament_id', sa.String(length=24), nullable=False),
    sa.Column('filamentdb_spool_id', sa.String(length=24), nullable=False),
    sa.Column('filament_mapping_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_mapping_id'], ['filament_mappings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolman_spool_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spool_mappings')
    op.drop_table('sync_log')
    op.drop_table('snapshots')
    op.drop_table('filament_mappings')
    op.drop_table('conflicts')
    op.drop_table('bridge_config')
    # ### end Alembic commands ###
