"""Unified dry-run plan for the Dashboard (FR-14).

Produces a CycleResult with preview entries for ALL records regardless of
bridge state:
  - Already-linked pairs  → steady-state diff via run_sync_cycle
  - Cross-ref orphans     → update (re-link from existing cross-ref extra)
  - Unlinked SM filaments → matcher auto-decisions → planner (create/update/conflict)

Never writes to either upstream system.
"""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session

from app.config import settings as _settings
from app.core.engine import CycleResult, _preview_label, _read_config, run_sync_cycle
from app.core.matcher import match_filaments
from app.core.planner import _plan_spoolman_to_fdb
from app.models.mapping import FilamentMapping, SpoolMapping
from app.schemas.spoolman import SpoolmanFilament, decode_extra_value

logger = logging.getLogger(__name__)


def _filament_label(sm: SpoolmanFilament) -> str:
    vendor = sm.vendor.name if sm.vendor else ""
    base = " ".join(p for p in [vendor, sm.name, sm.color_hex] if p)
    return base or f"SM filament #{sm.id}"


async def plan_dry_run(db: Session, spoolman, filamentdb) -> CycleResult:
    """Unified matcher-driven dry-run plan (FR-14).

    Delegates already-linked pair diffs to run_sync_cycle, then augments the
    result with cross-ref orphans and matcher-driven unlinked-record entries.
    """
    # 1. Steady-state diff for already-linked spool pairs.
    result = await run_sync_cycle(db, spoolman, filamentdb, dry_run=True)

    # 2. Load mapping state needed to identify unlinked records.
    spool_mappings = db.query(SpoolMapping).all()
    fil_mappings = db.query(FilamentMapping).all()
    mapped_sm_spool_ids: set[int] = {m.spoolman_spool_id for m in spool_mappings}
    mapped_sm_filament_ids: set[int] = {m.spoolman_filament_id for m in fil_mappings}
    mapped_fdb_filament_ids: set[str] = {m.filamentdb_id for m in fil_mappings}

    # 3. Fetch upstream state for unlinked-record handling.
    try:
        sm_filaments = await spoolman.get_filaments()
        sm_spools = await spoolman.get_spools()
        fdb_filaments = await filamentdb.get_filaments()
    except Exception as exc:
        logger.error("plan_dry_run: upstream fetch failed: %s", exc)
        result.errors += 1
        return result

    active_sm_spools = [s for s in sm_spools if not s.archived]

    # 4. Remove false conflicts generated by run_sync_cycle for SM spools whose
    #    filament has no FilamentMapping.  run_sync_cycle → _handle_new_sm_spool
    #    buckets these as conflict("new_spool"); the planner below re-classifies them.
    #
    #    Also remove conflicts for cross-ref orphans (xref present, no SpoolMapping):
    #    after the stale-xref fix, the engine falls through to _handle_new_sm_spool
    #    for stale xrefs, producing a spurious conflict. Step 5 re-classifies these
    #    as "update (re-link)" so the conflict must be removed here first.
    false_conflict_sm_ids: set[int] = set()
    for sm_spool in active_sm_spools:
        if sm_spool.id in mapped_sm_spool_ids:
            continue
        xref = decode_extra_value(sm_spool.extra.get(_settings.spoolman_field_filamentdb_spool_id))
        if xref:
            # Cross-ref orphan: step 5 will emit a proper "update (re-link)" entry.
            # Remove any new_spool conflict the engine generated (stale xref falls
            # through to _handle_new_sm_spool when the referenced FDB spool is gone).
            false_conflict_sm_ids.add(sm_spool.id)
            continue
        if sm_spool.filament.id not in mapped_sm_filament_ids:
            false_conflict_sm_ids.add(sm_spool.id)

    if false_conflict_sm_ids:
        cleaned: list[dict] = []
        removed = 0
        for entry in result.preview:
            if (entry.get("action") == "conflict"
                    and entry.get("entity_type") == "spool"
                    and entry.get("field") == "new_spool"
                    and entry.get("spoolman_id") in false_conflict_sm_ids):
                removed += 1
            else:
                cleaned.append(entry)
        result.preview = cleaned
        result.conflicts -= removed

    # 5. Cross-ref orphans: SM spools with filamentdb_spool_id extra but no SpoolMapping.
    #    The engine silently drops these (continue at the xref guard). Classify as "update"
    #    because the cross-ref already encodes the mapping; a fresh bridge should re-link.
    cross_ref_spool_ids: set[int] = set()
    for sm_spool in active_sm_spools:
        if sm_spool.id in mapped_sm_spool_ids:
            continue
        xref = decode_extra_value(sm_spool.extra.get(_settings.spoolman_field_filamentdb_spool_id))
        if not xref:
            continue
        cross_ref_spool_ids.add(sm_spool.id)
        result.preview.append({
            "action": "update",
            "entity_type": "spool",
            "direction": "spoolman_to_filamentdb",
            "label": _preview_label(sm_spool=sm_spool),
            "field": None,
            "old": None, "new": None,
            "reason": "re-link from existing cross-ref",
            "candidates": None,
            "spoolman_id": sm_spool.id,
            "fdb_filament_id": None,
            "fdb_spool_id": xref,
        })
        result.updated += 1

    # 6. Matcher-driven plan for unlinked SM filaments (spoolman→filamentdb only).
    config = _read_config(db)
    import_direction = config.get("import_direction", "spoolman")
    unlinked_sm_filaments = [f for f in sm_filaments if f.id not in mapped_sm_filament_ids]

    if not unlinked_sm_filaments or import_direction != "spoolman":
        return result

    unlinked_fdb_filaments = [f for f in fdb_filaments if f.id not in mapped_fdb_filament_ids]
    mr = match_filaments(unlinked_sm_filaments, unlinked_fdb_filaments)

    # Build auto-decisions from matcher results.
    decisions_by_sm: dict[int, dict] = {}
    for pair in mr.matched:
        decisions_by_sm[pair.spoolman_filament.id] = {
            "action": "link",
            "filamentdb_id": pair.fdb_filament.id,
        }
    for sm_f in mr.unmatched_spoolman:
        decisions_by_sm[sm_f.id] = {"action": "create"}

    # Ambiguous SM filaments → conflict entries (never auto-pick, hard rule).
    ambiguous_sm_ids: set[int] = set()
    for sm_f, candidates in mr.ambiguous:
        ambiguous_sm_ids.add(sm_f.id)
        label = _filament_label(sm_f)
        result.preview.append({
            "action": "conflict",
            "entity_type": "filament",
            "direction": "spoolman_to_filamentdb",
            "label": label,
            "field": "filament_match",
            "old": None, "new": None,
            "reason": f"ambiguous — {len(candidates)} FDB candidates",
            "candidates": [c.id for c in candidates],
            "spoolman_id": None,
            "fdb_filament_id": None,
            "fdb_spool_id": None,
        })
        result.conflicts += 1
        # Each unmapped, non-orphan spool of the ambiguous filament also conflicts.
        for sm_spool in active_sm_spools:
            if sm_spool.filament.id != sm_f.id:
                continue
            if sm_spool.id in mapped_sm_spool_ids or sm_spool.id in cross_ref_spool_ids:
                continue
            result.preview.append({
                "action": "conflict",
                "entity_type": "spool",
                "direction": "spoolman_to_filamentdb",
                "label": f"{label} (SM #{sm_spool.id})",
                "field": "filament_match",
                "old": None, "new": None,
                "reason": f"parent filament ambiguous — {len(candidates)} candidates",
                "candidates": [c.id for c in candidates],
                "spoolman_id": sm_spool.id,
                "fdb_filament_id": None,
                "fdb_spool_id": None,
            })
            result.conflicts += 1

    # Run the planner for matched (link) and unmatched (create) SM filaments.
    precision = int(config.get("weight_precision_decimals", 2))
    plan = _plan_spoolman_to_fdb(
        db, sm_filaments, sm_spools, fdb_filaments,
        decisions_by_sm, {}, {},
        precision=precision,
    )

    # Emit filament-level plan entries.
    for item in plan.filament_items:
        if item.action == "skip" and not item.error:
            continue  # already-linked or no-decision — not surfaced here
        if item.sm_filament.id in ambiguous_sm_ids:
            continue  # already emitted as conflict

        label = _filament_label(item.sm_filament)
        if item.action == "create":
            result.preview.append({
                "action": "create",
                "entity_type": "filament",
                "direction": "spoolman_to_filamentdb",
                "label": label,
                "field": None,
                "old": None, "new": None,
                "reason": None,
                "candidates": None,
                "spoolman_id": None,
                "fdb_filament_id": None,
                "fdb_spool_id": None,
            })
            result.created += 1
        elif item.action == "link":
            result.preview.append({
                "action": "update",
                "entity_type": "filament",
                "direction": "spoolman_to_filamentdb",
                "label": label,
                "field": "filament_link",
                "old": None, "new": item.fdb_id,
                "reason": "matched to existing FDB filament",
                "candidates": None,
                "spoolman_id": None,
                "fdb_filament_id": item.fdb_id,
                "fdb_spool_id": None,
            })
            result.updated += 1
        elif item.error:
            result.preview.append({
                "action": "skip",
                "entity_type": "filament",
                "direction": "spoolman_to_filamentdb",
                "label": label,
                "field": None,
                "old": None, "new": None,
                "reason": item.error,
                "candidates": None,
                "spoolman_id": None,
                "fdb_filament_id": item.fdb_id,
                "fdb_spool_id": None,
            })
            result.errors += 1

    # Emit spool-level plan entries.
    for si in plan.spool_items:
        if si.sm_spool.id in mapped_sm_spool_ids:
            continue  # already mapped; handled by run_sync_cycle
        if si.sm_spool.id in cross_ref_spool_ids:
            continue  # cross-ref orphan; already emitted as update in step 5
        if si.fil_item.sm_filament.id in ambiguous_sm_ids:
            continue  # already emitted as conflict
        # Spools of already-linked filaments are handled by run_sync_cycle's new-spool detection.
        if si.fil_item.action == "skip" and si.fil_item.detail == "already linked":
            continue
        if si.action == "skip":
            continue  # planner's "already linked" catch-all

        label = f"{_filament_label(si.fil_item.sm_filament)} (SM #{si.sm_spool.id})"
        result.preview.append({
            "action": "create",
            "entity_type": "spool",
            "direction": "spoolman_to_filamentdb",
            "label": label,
            "field": None,
            "old": None, "new": None,
            "reason": None,
            "candidates": None,
            "spoolman_id": si.sm_spool.id,
            "fdb_filament_id": si.fdb_filament_id,
            "fdb_spool_id": None,
        })
        result.created += 1

    return result
